### ISSUE TITLE
Please stop stealing code from etcd raft

### ISSUE THREAD

**Issue by lni** [tiglabs/raft#11]
ETCD Raft is released under the Apache2 license, 

Item 4(b) of the Apache2 license explicitly requires all of your derived code to "carry prominent notices stating that You changed the files;"

As of writing, there is NO such notice given in any of those source files modified from etcd raft's code. 

e.g. there is no notice given stating that this is modified from etcd raft's code
https://github.com/tiglabs/raft/blob/master/raft_log_unstable.go?ts=2

Note that the above file is just one example, you have to put modification notice in every single file that contains code derived from etcd raft. 

Item 4(c) of the Apache2 license explicitly requires that "You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work". 

As of writing, ETCD raft's original copyright information has been intentionally removed/replaced from all etcd raft source files. 

e.g. etcd raft's copyright information included in its log_unstable.go file has been intentionally removed
https://github.com/tiglabs/raft/blob/master/raft_log_unstable.go?ts=2

Note that the above file is just one example, you have to keep etcd's copyright information in every single source file that contains code derived from etcd raft. 

Item 4(d) of the Apache2 license explicitly requires etcd's NOTICE file with its full content to be included in your repo. The license requires that "If the Work includes a NOTICE text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file". 

As of writing, etcd's NOTICE file has not been included anywhere in your repo. 

Maybe talk to your corporate IP attorney before stealing code? I am pretty sure that not all of your corporate attorneys are busy working in Minnesota.

**Comment by bladehliu** [comment]
this pkg was based on etcd/raft, thanks in readme. licence was in vendor however notice was forgotten. thank you @lni

**Comment by lni** [comment]
@bladehliu please stop your non-sense. 

I cloned the project before notifying you guys, there is conclusive evidence showing you intentionally removed etcd's copyright information and recently replaced it with your project's name as the new copyright owner.

**Comment by yenshih** [comment]
@bladehliu Shame on you

**Comment by Justineo** [comment]
Actually if you didn’t honor the requirements of etcd’s license, especially after you removed, you have already lost the license authorization of the original author.

Removing copyright is obviously intentional, and I believe this issue is not just a “reminder”. If the project is based on etcd/raft, then at least don’t use vague words like “inspired” please.

**Comment by lni** [comment]
@Justineo 

Please don't over estimate jd.com's moral standard when it comes to Copyright/IP compliance. It is also clear that @bladehliu is not a technical leader of the team but merely a junior corporate politician.

**Comment by Xsmael** [comment]
waw, i never new things like that happens!
