### ISSUE TITLE
Story on how you get caught when stealing etcd raft's code

### ISSUE THREAD

**Issue by lni** [tiglabs/raft#12]
https://zhuanlan.zhihu.com/p/45820085

**Comment by mervinkid** [comment]
There is no intention to offend, but I always think that the word `stealing` is excessive, which can be `copyright issues`.
We will correct our mistakes.
Thank you for your guidance.

**Comment by byteink** [comment]
我是这个代码库的维护者，原本这个项目其实只是个内部用的，后来因为别的项目需要引用我放了上来，目的并不是开源并向外界宣言是我们完全自己开发的，由于我的疏忽主观上没有认为是开源，对开源的规范不够重视，相关copyright和license都缺失。这两天国庆加班正在梳理，第一步先加了我们的copyright，现在正在梳理etcd代码的范围再补齐etcd的copyright和license。现在看到的只是个中间状态，并不是想把代码占为己有。请大佬们给我们一个改正错误的时间吧。

**Comment by lni** [comment]
@mervinkid 

Stealing is stealing. If someone took ContainerFS's code, removed all copyright information from it, put it into a new github.com repo and started claiming that he/she is now the copyright owner, how would you describe that? Copyright issue? 

There is actually very practical and easy way to stop people from calling your project "code stealing"  - not to steal code in the first place.
